;; Colors

(deftheme blah "My custom colors over the default set")
(let ((fg           "wheat")
      (bg           "#000000")
      (steelblue    "#4682b4")
      (searchcolor1 "#228b22")
      (searchcolor2 "#6b8e35")
      (searchcolor3 "#556b2f")
      (selected     "#00868b")
      (dgreen       "#00aa00")
      (indianred    "#cd5c5c")
      (skyblue      "#00bfff")
      (red          "#ff0000")
      (yellow       "#ffff00")
      (green        "#00ff00")
      (white        "#ffffff")
      (magenta      "#ff00ff")
      (lightgreen   "#adff2f")
      (baregray     "#666666"))
  (custom-theme-set-faces
   'blah
   `(default                           ((t (:foreground ,fg :background ,bg))))
   `(mode-line                         ((t (:foreground ,fg :background ,steelblue))))
   `(swiper-line-face                  ((t (:foreground ,white :background ,baregray))))
   `(swiper-match-face-1               ((t (:foreground ,white :background ,baregray))))
   `(region                            ((t (:background ,selected))))
   `(diff-hl-insert                    ((t (:background ,dgreen))))
   `(diff-hl-delete                    ((t (:background ,indianred))))
   `(diff-hl-change                    ((t (:background ,skyblue))))
   `(hl-line                           ((t (:background ,baregray))))
   `(font-lock-warning-face            ((t (:foreground ,red :weight bold))))
   `(persp-selected-face               ((t (:foreground ,green :weight bold))))
   ;; `(rainbow-delimiters-unmatched-face ((t (:inherit 'error))))))
))

(provide 'my-colors)
